### ISSUE TITLE
Wrong annualization of Sortino Ratio?

### ISSUE THREAD

**Issue by gabrieleiacono** [quantopian/empyrical#61]
The Sortino Ratio is annualized in stats.py as follows:
`return sortino * ann_factor`

where `ann_factor` is
`ann_factor = annualization_factor(period, annualization)`

I believe you actually meant to return
`return sortino * np.sqrt(ann_factor)`

just like you did with the Sharpe Ratio.

**Comment by twiecki** [comment]
Good catch, want to do a PR?

**Comment by rsheftel** [comment]
The math is actually correct in the existing version. The confusion is because of where the `ann_factor` multiplication occurs. The reason it is correct is because the calculation of the downside risk with the `downside_risk` function returns an annualized value, it does the `* np.sqrt()` in that function. The calculation of the numerator of returns in the `sortino_ratio()` function does not annualize:

`mu = nanmean(adj_returns, axis=0)` so the code annualizes at the end at the return value.
`return sortino * ann_factor'

Agree this is confusing, so I submitted a pull request that just moves the `* ann_factor` to the line that calculates the returns so the math is more obvious:

`mu = nanmean(adj_returns, axis=0) * ann_factor`

**Comment by twiecki** [comment]
@rsheftel Thanks, very glad you point this out before we merged it.

**Comment by twiecki** [comment]
Closed by #74.

**Comment by gabrieleiacono** [comment]
I'm terribly sorry, thank you @riabaldevia for finding my mistake. It is much better now, after PR #74.
